### ISSUE TITLE
Error: Forbidden...

### ISSUE THREAD

**Issue by telkins** [bluematador/cloud-core#8]
Hi.  New user of cloud-core, but unable to get it to work.  I followed the instructions from the video, creating a new programmatic user, giving it the global ReadOnlyAccess permission, and then copying pasting the credentials into both my local instance as well as your own.

When I enter submit, it immediately begins to list services, but they all start to "error out", displaying "Error: Forbidden" in the forecast column.

I'm not quite sure where to begin.  I've poked around to compare my two IAM users and they both seem to have access to the couple of services I queried (in the AWS IAM Access Advisor).  I also watch the video several more times to see if I missed something.

Any advice?

Thanks.

**Comment by telkins** [comment]
Looks like it might be related to this: https://github.com/Rob--W/cors-anywhere/issues/301

Seems requests from cloud-core are being made to https://cors-anywhere.herokuapp.com:
* https://cors-anywhere.herokuapp.com/calculator.aws/pricing/2.0/meteredUnitMaps/apigateway/USD/current/apigateway.json
* https://cors-anywhere.herokuapp.com/calculator.aws/pricing/2.0/meteredUnitMaps/cloudwatch/USD/current/cloudwatch.json
* https://cors-anywhere.herokuapp.com/calculator.aws/pricing/2.0/meteredUnitMaps/events/USD/current/events.json
* etc

Maybe...? 🤔

**Comment by telkins** [comment]
There's also this: https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default

When I temporarily enable the cors-anywhere service (?), then it seems that cloud-core fires off more requests, a great deal of them to aws, many/all of which seem to respond with a 403 and a referrer policy of "strict-origin-when-cross-origin".

I'm out of my depth here....  😳

**Comment by mbarlocker** [comment]
Yes, this whole application, being a frontend app only, relies on a CORS delivery service. There are many out there. If the one I chose doesn't work anymore, I would recommend testing another one. Always open to pull requests.

**Comment by telkins** [comment]
Thanks for the reply/info.  I'm not familiar with CORS delivery services, although I can imagine what they provide, so I won't worry about it until there's a need.

(Temporarily enabling the cors-anywhere service seems to work after all.  Not sure what happened earlier.)
